### ISSUE TITLE
Create Rib allways fails with: 'NoneType' object has no attribute 'extrude'

### ISSUE THREAD

**Issue by stumpfwald** [FredsFactory/FreeCAD_AirPlaneDesign#31]
Regardless which airfoil I choose (the 2 Epplers provided or another one) the new rib allways has an error.
The Report View shows: 
File "/home/gerhard/.FreeCAD/Mod/AirPlaneDesign/airPlaneRib.py", line 85, in execute
    fp.Shape = face.extrude(FreeCAD.Vector(0,fp.Thickness,0))
<class 'AttributeError'>: 'NoneType' object has no attribute 'extrude'

face returned by process in airPlaneAirFoil.py is allways None.

**Comment by FredsFactory** [comment]
Hello,
thank for your issue. Can you confirm the release of freecad that you use ?
I can reproduce the issue on the V0.18 but it works on V0.19.
Fred

**Comment by stumpfwald** [comment]
Hello,
I use V0.18.1, the version provided with OpenSUSE 15.1. I could also test V0.18.4 from a community repository with the same result.
Gerhard

**Comment by FredsFactory** [comment]
Hello,
I corrected the issue, I'm not being under linux, could you test it?
Fred

**Comment by FredsFactory** [comment]
Tested on windows 10 and Mac OS X, on V0.18-16146 and V0.19-21329.

**Comment by stumpfwald** [comment]
Hello,
thank you.
Test with V0.18.1 in OpenSUSE 15.1 succeeded.
Gerhard

**Comment by FredsFactory** [comment]
Thank for you contribution 
Frédéric
